
name: ttps-ruby

services:
  web:
    build:
      context: ../src
      dockerfile: ../Docker/Dockerfile
    command: foreman start -f Procfile.dev
    volumes:
      - ../src:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
      - "5173:5173"
    stdin_open: true
    tty: true
    user: "1000:1000"

volumes:
  bundle_cache: